-- Create APC Payments table
CREATE TABLE IF NOT EXISTS apc_payments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id VARCHAR(255) UNIQUE NOT NULL,
  cashfree_order_id VARCHAR(255),
  cashfree_payment_id VARCHAR(255),
  
  -- Author Information
  author_name VARCHAR(255) NOT NULL,
  author_email VARCHAR(255) NOT NULL,
  author_phone VARCHAR(20) NOT NULL,
  manuscript_id VARCHAR(100) NOT NULL,
  
  -- Payment Details
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(3) DEFAULT 'INR',
  payment_status VARCHAR(50) DEFAULT 'PENDING',
  payment_method VARCHAR(100),
  
  -- GASF Membership
  gasf_membership VARCHAR(50),
  is_member BOOLEAN DEFAULT FALSE,
  discount_applied INTEGER DEFAULT 0, -- Percentage
  
  -- Metadata
  metadata JSONB DEFAULT '{}',
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_apc_payments_order_id ON apc_payments(order_id);
CREATE INDEX IF NOT EXISTS idx_apc_payments_cashfree_order_id ON apc_payments(cashfree_order_id);
CREATE INDEX IF NOT EXISTS idx_apc_payments_author_email ON apc_payments(author_email);
CREATE INDEX IF NOT EXISTS idx_apc_payments_manuscript_id ON apc_payments(manuscript_id);
CREATE INDEX IF NOT EXISTS idx_apc_payments_status ON apc_payments(payment_status);
CREATE INDEX IF NOT EXISTS idx_apc_payments_created_at ON apc_payments(created_at);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

CREATE OR REPLACE TRIGGER update_apc_payments_updated_at
    BEFORE UPDATE ON apc_payments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Add RLS policies (Row Level Security)
ALTER TABLE apc_payments ENABLE ROW LEVEL SECURITY;

-- Policy for service role (full access for backend)
CREATE POLICY "Service role can manage all payments" ON apc_payments
  FOR ALL USING (auth.role() = 'service_role');

-- Policy for authenticated users (read their own payments)
CREATE POLICY "Users can view their own payments" ON apc_payments
  FOR SELECT USING (author_email = auth.jwt() ->> 'email');

-- Add comments for documentation
COMMENT ON TABLE apc_payments IS 'Store APC (Article Processing Charge) payment records for IJCAST journal';
COMMENT ON COLUMN apc_payments.order_id IS 'Unique order identifier generated by the application';
COMMENT ON COLUMN apc_payments.cashfree_order_id IS 'Order ID returned by Cashfree payment gateway';
COMMENT ON COLUMN apc_payments.cashfree_payment_id IS 'Payment ID returned by Cashfree after successful payment';
COMMENT ON COLUMN apc_payments.payment_status IS 'Payment status: INITIATED, PENDING, SUCCESS, FAILED, CANCELLED';
COMMENT ON COLUMN apc_payments.gasf_membership IS 'GASF membership number for discount eligibility';
COMMENT ON COLUMN apc_payments.discount_applied IS 'Discount percentage applied (40% for GASF members)';
COMMENT ON COLUMN apc_payments.metadata IS 'Additional data including payment details, calculations, etc.';